### ISSUE TITLE
[Query]

### ISSUE THREAD

**Issue by Tabs16** [haccer/twint#100]
Can we extract tweets at a "particular time" since a date? I have noticed that all the tweets start getting extracted from 23:59:59 if I put since "date" to until "date" 
TIA !

**Comment by pielco11** [comment]
The advanced search of Twitter does not have a specific parameter for that. 

But we can add an argument to save/filter out tweets for a specific time range (e.g. from 2:00 a.m. to 4:30 a.m.) if this is what you mean

**Comment by Tabs16** [comment]
is it achieved through timedelta @haccer ?

**Comment by pielco11** [comment]
The `timedelta` arg is used to define a number of days to search Tweets for

We are working hard on upcoming features and stuff, if you know how to play with python you should do something that does what `until` and `since` args do
