### ISSUE TITLE
pip3 install error

### ISSUE THREAD

**Issue by psubbiah** [haccer/twint#101]
### Initial Check 
Make sure you've checked the following.

- [] Python version is 3.5 or higher.
- [] Using the latest version of Twint. 

Using Python 3.6.4 Anaconda Custom
Downloaded today

### Command
- pip install twint
- pip3 install -r requirements.txt
- pip3 install cchardet

all commands give the same error

### Description of Issue
In file included from src/pycares.h:7:
    /Users/ale/anaconda3/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1

Command "/Users/ale/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xm/z9124yp13b12d8501v8wzkxr0000gn/T/pip-install-3qna7xkb/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xm/z9124yp13b12d8501v8wzkxr0000gn/T/pip-record-dn_m681e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xm/z9124yp13b12d8501v8wzkxr0000gn/T/pip-install-3qna7xkb/pycares/

when running it also says: 
Failed building wheel for cchardet
Failed building wheel for pycares
I have also tried: export CXX=clang; pip3 install twint, as I noticed that the Darwin
error: command 'clang' failed with exit status 1

clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin17.5.0 is different from the one giving the error.

### OS Details
Using MacOS High Sierra 10.13.4

**Comment by alexsieusahai** [comment]
Do you have the latest version of setuptools?

If that does not try the problem try following similar steps listed here:
https://github.com/pythonnet/pythonnet/issues/465

**Comment by psubbiah** [comment]
I also see this: 

In file included from src/pycares.h:7:
    /Users/ale/anaconda3/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>

**Comment by psubbiah** [comment]
Resolved!! Had to make sure that Xcode’s command-line tools were properly installed. This solved the issue: xcode-select --install. Thanks though!
