### ISSUE TITLE
Search tips

### ISSUE THREAD

**Issue by hudmb** [haccer/twint#103]
Not sure if this is the right place to post, but I found a really useful site which details some advanced Twitter search parameters. Maybe Cody could confirm if they should work within the search query in his code? 

https://www.labnol.org/internet/twitter-search-tricks/13693/

**Comment by haccer** [comment]
Yes this is an appropriate place to post, I can use this issue to reference if someone has a question that relates to this.
--

Anyways, Twint uses a lot of these and you can definitely add or use other search operators by including them in the search option like:
```
-s "min_retweets:10 filter:news"
```

Also it's good to make use of the `AND` & `OR` in the search parameter to get Tweets that have different topics. The blog you shared explains that a little bit.
