### ISSUE TITLE
[Query]

### ISSUE THREAD

**Issue by Tabs16** [haccer/twint#104]
It seems quite weird to me as today I am not able to fetch any tweets, the "twint.Search()" is not working even though I haven't made any changes to my code.
What can be the possible reasons?

**Comment by buckket** [comment]
Same problem here. Seems like Twitter updated their HTML code and thus the parser doesn’t recognize the data anymore.

**Comment by haccer** [comment]
@Tabs16 @buckket 
I fixed it earlier after seeing this https://github.com/haccer/twint/issues/102

pls update to the latest version, everything should work fine now

**Comment by Tabs16** [comment]
@haccer is it updated in the python module as well?
