### ISSUE TITLE
Dout with commands in Command Prompt

### ISSUE THREAD

**Issue by DavidPerea** [haccer/twint#105]
### Initial Check 
I have made sure to check the following.

- [] Python version is 3.6.2
- [] Using the latest version of Twint.

### Command
After having generated the file "twint.py" and save it on my desktop. I am going to run the following code in the Command Prompt:

`python twint.py -u malaga -o file.csv --csv`

I pretend to get all the tweets in csv from the twitter account @malaga.
But It does not run. It returns the following error:
```
Traceback (most recent call last):
  File "twint.py", line 152, in <module>
    main()
  File "twint.py", line 140, in main
    c = initialize(args)
  File "twint.py", line 66, in initialize
    c = twint.Config()
AttributeError: module 'twint' has no attribute 'Config'
```

### Description of Issue
Therefore, I do not understand why I have this error. If I have previously all properly installed. When I want to use the combos in the Command Prompt it returns that error to me.

Can you help me? please

### OS Details
I am using Windows 10.

**Comment by haccer** [comment]
twint.py needs to be renamed somethings that's not 'twint', otherwise it's trying to import itself. 

See [issue #92](https://github.com/haccer/twint/issues/92) for more details

**Comment by DavidPerea** [comment]
Great, perfect. Solved. Thanks for your time.
