### ISSUE TITLE
[REQUEST] Make twint object return values

### ISSUE THREAD

**Issue by mathsten** [haccer/twint#107]
Awesome tool! I would love to also have the twint objects return values when called, not only parsed into a csv file or database. Would this be possible?

For example if writing `friends = twint.Following(c)` actually would return a list of all the users friends.

**Comment by haccer** [comment]
Duplicate of https://github.com/haccer/twint/issues/86

--

This is something I've been working towards, right now objects won't return due to the way the loops are configured.
