### ISSUE TITLE
Until argument preventing scraping

### ISSUE THREAD

**Issue by MicahNus** [haccer/twint#111]
### Initial Check 
Make sure you've checked the following.

- [x] Python version is 3.5 or higher.
Python 3.6
- [x] Using the latest version of Twint.
Just cloned a new copy to check.

### Command
Please provide the exact command ran including the username/search so I may reproduce the issue.
python twint.py -s USA  --until 2017-05-17 -o file.csv --csv

### Description of Issue
Please use as much detail as possible.
I'm trying to grab tweets up to a certain point using the --until argument, however, nothing is being returned. Occurs when using the command line and when using as a module. Adding a --since argument doesn't help. I've run the debugger included in VSCode and the URL being generated is valid and displays on Twitter, but nothing appears in Twint.
A different search 'python twint.py -s OWLMVP --until 2017-05-17 -o file.csv --csv' works to a point (--until 2018-05-14 is where it stops for me).

### OS Details
Using Windows, Linux? What OS version?
PC1: 
Windows 10 1803 Build 17134.48
Python 3.6.4

PC2: 
Windows 10 1803 Build 17134.48
Python 3.6.5

**Comment by haccer** [comment]
Hi @MicahNus, 

Thanks, I'll take a look at this right now

**Comment by haccer** [comment]
Very strange,

Seems this is an issue with Twitter itself as no results show:

https://twitter.com/search?f=tweets&vertical=news&q=usa%20until%3A2017-05-17&src=typd
https://twitter.com/search?f=tweets&q=OWLMVP%20until%3A2017-05-17&src=typd

**Comment by haccer** [comment]
Do let me know if you get results from either of those links

**Comment by haccer** [comment]
It appears i get results when authenticated, but none when not authenticated

**Comment by MicahNus** [comment]
If I open both links in an incognito browser window, I still get results.

**Comment by haccer** [comment]
@MicahNus quick question, what browser are you using? Chrome?

**Comment by MicahNus** [comment]
Chrome 66.0.3359.181

**Comment by haccer** [comment]
Strange, I'm going to wait a bit until I can properly look at this... using the `until` operator in Chrome incognito browser doesn't work for me at all atm

Might be an issue w/ Twitter or it might not... maybe @pielco11 can help

**Comment by haccer** [comment]
Okay they've blacklisted the user-agent I've been using it looks like LOL.... going to add a different one that appears to be working in a sec.

**Comment by haccer** [comment]
Okay, I've added a new user agent; please try now and let me know how it goes

**Comment by MicahNus** [comment]
New agent has done the trick! Cheers for the fast fix!

**Comment by haccer** [comment]
Awesome!

**Comment by pielco11** [comment]
#113
