### ISSUE TITLE
Several Users - use file as userlist arg ~Pielco11

### ISSUE THREAD

**Issue by DavidPerea** [haccer/twint#112]
Is there the option to get the tweets of several users in the same CSV file? That is, with a command like this: 

`python Twint.py -u ursername -o file.csv --csv`

How can I add more than one user to get all their tweets at the same time?

I had thought about looping or creating a list. But in the Command Prompt it does not allow it. So I would not know how I could do it.

**Comment by pielco11** [comment]
Hi, I added a new arg, `userlist`, to let you do so. Try with something like `python Twint.py --userlist user1,user2 -o file.csv --csv`

**Comment by DavidPerea** [comment]
Great!!! 
It works perfectly. 
Thank you very much for your input.

**Comment by pielco11** [comment]
You can also parse files as input, nothing change just do `python Twint.py --userlist path/to/file.txt --csv -o file.csv` be sure to have one user for line

**Comment by DavidPerea** [comment]
The truth is that it is very useful to analyze files as input.
However, I have used the command that you have given me, indicating the TXT file address, but I do not know why I extracted tweets from other users. I've put the users well and one on each line.
It's very strange.

**Comment by pielco11** [comment]
Hmmm, going to check right now!

**Comment by pielco11** [comment]
Now it works, there were `readline` instead of `readlines` but with the 2nd one you had annoying `\n`

**Comment by DavidPerea** [comment]
Nothing. The same thing keeps happening to me. That is to say that it analyzes other users and not those that I have the TXT file.
I do not know if I'm doing something wrong. But I have a user per line and I put the address of entries well. So I do not know.

**Comment by pielco11** [comment]
Ok, now it uses abspath, should work!

**Comment by DavidPerea** [comment]
Would it be something like this?

`python Twint.py --userlist os.path.abspath("user.txt") --csv -o file.csv`

I do not know very well how to use **abspath**

**Comment by pielco11** [comment]
Don't worry about that, the abspath is included in the code. Just try as earlier `python Twint.py --userlist path/to/file.txt --csv -o file.csv`

**Comment by DavidPerea** [comment]
Nothing. The same thing keeps happening to me. I do not know why. But do not worry, I will put one by one the users in the code. But it is strange.

**Comment by pielco11** [comment]
Really really strange

![screenshot_17](https://user-images.githubusercontent.com/17363750/40540501-b2aa758e-6018-11e8-9a5c-f5eb66f12a57.png)

**Comment by DavidPerea** [comment]
This happens to me. I have the txt document on my desktop and when I run the command it does not return the tweets from this users. If not of others. And I have tried to put the address of the txt document in different ways and nothing.

![ima](https://user-images.githubusercontent.com/33260230/40540958-4142d5e2-601a-11e8-83bf-7d9995c0d70c.png)

**Comment by pielco11** [comment]
Hmm, maybe with Windows there are problems with slashes... 

Can you add `print(url)` in `twint/get.py` at line 73, please? 
So that you have something like:
```python
    self.config.Near = self.config.Near.replace(",", "%2C")
    url+= "%20near%3A{0.Near}".format(self.config)
    print(url)
return url
```

Try adding the line and post the output, please

**Comment by pielco11** [comment]
In `Twint.py` can you also do

(lines 59-60)
```python
def loadUserList(ul):
    print(os.path.abspath(ul))
    if os.path.exists(os.path.abspath(ul)):
```
please?

**Comment by haccer** [comment]
I've only read this briefly, but on Windows use \ instead of / for path to file:
Example:
`Desktop\file.txt`

**Comment by pielco11** [comment]
@DavidPerea While we try to find a solution, I suggest you to use a string as `--userlist` arg

Sorry for the inconvenience

**Comment by DavidPerea** [comment]
Nothing. Upside down. Thank you very much for the help and the contribution of the string as `--userlist`.
I will do so meanwhile.

**Comment by DavidPerea** [comment]
Sorry to ask again here.

But I've been working with strings as `userlist ` arg but it gives me a problem. And it happens when I put **more than 25 users** does not get tweets.

So see if you know how to solve this problem and increase the limit of users. That now stands at 25 users.

**Comment by pielco11** [comment]
Hmm, well I tried something and I can get results with no more than 27 users 

To be sure that's not an issue with Twint, try printing the url and search with the browser

**Comment by GeekOnAcid** [comment]
@pielco11 Thank you for the amazing tool for scraping Twitter. I'm facing the same issue with the user limit of ~25 when getting usernames from the text file (my file has ~1000 usernames). I'm using it with time range to get tweets from specific period from all users in txt file: `twint --userlist parth/to/file.txt --since 2018-07-01 --until 2018-09-19 -o file.csv --csv` The error is `CRITICAL:root:twint.run:Twint:Feed:noData'items_html` which I know you've discussed also in #360 

Is there any way around those limits? I guess I could loop through my list 20 at the time but I'm new to Python so making this loop is quite tricky for me. Any other solutions that emerged since you've discussed it here?

**Comment by pielco11** [comment]
@GeekOnAcid that limit is imposed by Twitter. You would have to split your file in chunks of 25 users and then run the command with every list
