### ISSUE TITLE
it does not get tweets older than 10 days

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#113]
### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```python
import twint
import MySQLdb
from twint import db

c = twint.Config()

# equivalent to `-s` bitcoin    para hacer el or %20OR%20  El %20 es un AND lógico
c.Search = "3dprinter"
    
c.Since = "2017-09-01"
c.Until = "2018-05-15"
c.Count = True
c.Limit = "20"
twint.Search(c) 
```

### Description of Issue
>Please use **as much detail as possible.**
it does not get tweets older than 10 days, the result is 0 Tweets
I think it worked fine yesterday :(

but if I do the search in twitter I get results:
https://twitter.com/search?l=&q=3dprinter%20since%3A2016-12-05%20until%3A2018-05-15&src=typd

any idea about the root cause?

### OS Details
>Using Windows, Linux? What OS version?

**Comment by pielco11** [comment]
Are you sure that you are running the latest version? I get results since 2017-09-16

**Comment by Nestor75** [comment]
no, I am not useng the latest version but the previous one

I am going to merge my version with the latest one and I will try again

many thanks :)

**Comment by haccer** [comment]
@Nestor75 `pip install twint --upgrade`

**Comment by Nestor75** [comment]
thanks for the update command

I updated  to the latest code yesterday and it worked fine when I executed the query yesterday but today I am facing the same issue, I cannot get tweets older than 10 days. Is it possible that twitter ban somehow my queries bacuase I launched 5 different queries at the same time asking for many data?

**Comment by pielco11** [comment]
Hmmm really strange, I'm not having errors or problems with the latest update. I don't think that Twitter is banning queries because I can do a lot of requests simultaneously

**Comment by Nestor75** [comment]
it is really extrange, I am using exactly the same queries and code than yesterday. Yesteryda I got tones of tweets from 2017 and today I am getting 0 tweets :( I am lost :(

**Comment by pielco11** [comment]
Unfortunately I'm not able to replicate the problem so I don't really know how to help you investigating the issue, sorry about that

**Comment by Nestor75** [comment]
I will post if I find out the root cause. I have to say that I modified the code to store the info in Mysql but this changes do not affect to the feed code. If you are interented in this changes to support Mysql I will share with you the code

**Comment by pielco11** [comment]
That could be interesting, I'm re-designing the database for better analysis operations and stuff

Feel free to share the code via Pull Requests or opening a new issue (the first one is better for near big code enhancement)

About the cause, give us args that you are having errors with (with user, date range, etc.), please

**Comment by Nestor75** [comment]
I will do a pull requests and I write all the issues I faced and considerations to have. 

REgarding the current problem , this is the code:
================
import twint
c = twint.Config()

# equivalent to `-s` bitcoin    para hacer el or %20OR%20  El %20 es un AND lógico
c.Search = "3dprinter"
    

c.Since = "2017-09-01"
c.Until = "2018-05-16"
c.Count = True
#c.Lang = "es"
c.Limit = "20"


twint.Search(c) #obtiene los tweets y obtiene los datos de los usuarios que generan esos tweets

print("PROCESO FINALIZADO recoleccion tweets LANG ES")

**Comment by pielco11** [comment]
You can write considerations and comments in the pull requests, if you prefer

**Comment by haccer** [comment]
Your code works fine for me also

**Comment by Nestor75** [comment]
it's so weird. it does not get any tweet for me also using the original code. 

if i run this code only changing the until day i got 180 tweets even I have limietd to 20.
c.Until = "2018-05-17"

![image](https://user-images.githubusercontent.com/12037308/40576617-dfe438d2-60f9-11e8-8382-95076a087631.png)

if I use c.Until = "2018-05-16" i got nothing :(

![image](https://user-images.githubusercontent.com/12037308/40576642-1d9867f2-60fa-11e8-9962-c36779834cd3.png)

one more detail, I the version I have modified I also use tweepy for gathering data of the user using the Twitter API but... this latest tests I am using the original 1.1.2.6 version code

**Comment by haccer** [comment]
hmmm, well there's a lot of changes / optimizations that are going to be posted later today; some of which prevent the "Twitter changing" bugs we had the last few days from happening.... maybe then it'll work? I'll keep you posted.

**Comment by Nestor75** [comment]
many thanks :) you are a great team :)
