### ISSUE TITLE
output info issue

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#116]
### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
import twint

c = twint.Config()

c.Search = "3dprinter"
   
c.Since = "2017-09-01"
c.Until = "2017-10-16"
c.Count = True
c.Output="file.csv"
c.Store_csv = True
#c.Lang = "es"
c.Limit = "100"

twint.Search(c) #obtiene los tweets y obtiene los datos de los usuarios que generan esos tweets

### Description of Issue
the retweets numbers are not stored, I don't now exactly what the fields retweet and user_rt are for

I trried several queries and in all of them the field retweets is always blank.

![image](https://user-images.githubusercontent.com/12037308/40590662-f647c0a8-6202-11e8-9cd0-b82da4fa8e6b.png)

### OS Details
>Using Windows, Linux?linux  What OS version? ubuntu

**Comment by haccer** [comment]
The `retweet` field indicates whether the tweet was a retweeted tweet by the user indicated by `user_rt`... this is a new undocumented feature I've recently added, which you can use by using `twint.Profile` instead of `twint.Search`... it is limited tho.

**Comment by Nestor75** [comment]
that's great :)

I suppose the retweets number is not populated becasue it was not included in the CSV output code, isn't it?

**Comment by haccer** [comment]
yeah it wasn't, it should now tho
