### ISSUE TITLE
output csv and DB are different

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#117]
### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
the output to CSV and to DB is not the same, retweets, timestamp... it could be related also to the other output CSV issue

def writeCSV(Tweet, config):
    data = {
            "id": Tweet.id,
            "date": Tweet.datestamp,
            **"time": Tweet.timestamp,**
            "timezone": Tweet.timezone,
            "user_id": Tweet.user_id,
            "username": Tweet.username,
            "tweet": Tweet.tweet,
            "replies": Tweet.replies,
            "likes": Tweet.likes,
            "location": Tweet.location,
            "hashtags": Tweet.hashtags,
            "link": Tweet.link,
            "retweet": Tweet.is_retweet,
            "user_rt": Tweet.user_rt,
            "mentions": Tweet.mentions,
            }

def tweets(conn, Tweet):
    try:
        cursor = conn.cursor()
        entry = (Tweet.id,
                    Tweet.user_id,
                    Tweet.datestamp,
                    Tweet.timezone,
                    Tweet.location,
                    Tweet.username,
                    Tweet.tweet,
                    Tweet.likes,
                    **Tweet.retweets,**
                    ",".join(Tweet.hashtags),
                    Tweet.link,
                    Tweet.is_retweet,
                    Tweet.user_rt,
                    ",".join(Tweet.mentions))
        cursor.execute('INSERT INTO tweets VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)', entry)
        conn.commit()
    except sqlite3.IntegrityError:
        pass

### OS Details
>Using Windows, Linux? What OS version?

**Comment by haccer** [comment]
Thanks @Nestor75 for catching this,

I was a lil tired while pushing these updates a while ago and forgot to add those.

The latest commits include the missing entries, sorry about that

**Comment by Nestor75** [comment]
no problem at all :)
