### ISSUE TITLE
[Question] how do I install twint using a dockerfile?

### ISSUE THREAD

**Issue by johnhenryroadkill** [haccer/twint#1177]
Hello, I'm not very tech savvy so please forgive me if this is a dumb question.

I've been trying to install twint for a while using pip3 but everytime it fails when it tries to "build the wheel". I saw on the main page that I should try to install twint using a dockerfile but I have no idea what that is. Could someone please help me install Twint, either using pip3 or with the dockerfile? thank you

**Comment by klprint** [comment]
You first need to install docker on your system.

Then download the file called "Dockerfile" from this repo.

Next, run:

`sudo docker build . -t twint:latest`

This will create the container.

Finally, run:

`sudo docker run -it --rm twint`

This gives you a shell in the container and you can directly run twint within the container.
You can leave the container with `exit`.

For more details, checkout the [docker documentation](https://docs.docker.com/engine/reference/commandline/build/)

**Comment by tbennett6421** [comment]
Please consider adding this to the projects README.MD
