### ISSUE TITLE
twint -u username --following  CRITICAL:root:twint.feed:Follow:IndexError

### ISSUE THREAD

**Issue by areporeporepo** [haccer/twint#1182]
twint -u username --following 

CRITICAL:root:twint.feed:Follow:IndexError

**Comment by unautre** [comment]
Hello,
I am encountering the same kind of error. How did you fix it @anhagape ?

**Comment by areporeporepo** [comment]
need to use twitter API. fairly quick to get approved. if you run into rate limit for your app, you can email me. I can share how to get around it

**Comment by DV777** [comment]
> need to use twitter API. fairly quick to get approved. if you run into rate limit for your app, you can email me. I can share how to get around it

Hello, I am encountering this issue too. Could I send you an email ? I already installed tweepy and generated my twitter api credentials. The documentation is not helping a lot though - I am a true beginner with Python. 😅

**Comment by puddlejumper90** [comment]
> > need to use twitter API. fairly quick to get approved. if you run into rate limit for your app, you can email me. I can share how to get around it
> 
> Hello, I am encountering this issue too. Could I send you an email ? I already installed tweepy and generated my twitter api credentials. The documentation is not helping a lot though - I am a true beginner with Python. 😅

So... What is the point of this repo if we need to use the Twitter API?
