### ISSUE TITLE
SOLVED Twint command not working on kali

### ISSUE THREAD

**Issue by ENGO150** [haccer/twint#1189]
Hi, I am trying to use twint. I set everything, but when I try to use command "twint -u USER", it shows this:

Command 'twint' not found, did you mean:
  command 'twine' from deb twine
Try: sudo apt install <deb name>

What am I doing wrong?

**Comment by MikeTheScriptKid** [comment]
I'm having the same issue. Tried adding it to PATH, but no luck

**Comment by ghost** [comment]
same issue here, i found pipenv works for the moment but I dont want to use that.

**Comment by valmeza** [comment]
I have the same issue as well. I tried with both Kali and Ubuntu.

**Comment by CodeKilla01** [comment]
I am getting this syntax message 

refreshTokenException('Could not find the Guest token in HTML')
twint.token.RefreshTokenException: Could not find the Guest token in HTML

anyones know a workaround

**Comment by MikeTheScriptKid** [comment]
So I finally got the twint command working in Kali.
I added the following to /etc/environment
`/your_user/.local/bin` 
Then saved it and it worked.

**Comment by HarryWestFord** [comment]
sorry for being such a newbie but how excalty do you add this on the command line?

**Comment by hackingbutlegal** [comment]
`nano /etc/environment
`

**Comment by lonewolfrc** [comment]
Hey guys, it looks like I ran into a problem as the initial person that posted and reading through the everyone's comment. I am still having problems with twint not being found.

Command 'twint' not found, did you mean:
  command 'twine' from deb twine
Try: sudo apt install <deb name>

I added this to /etc/environment and saved, it still didn't work. 

PATH=/home/username/.local/bin this did not work, and I did try without the /home/ directory. 

Any ideas? Yes, I did power cycle.

**Comment by ChuloIva** [comment]
If you haven't found the answer yet, you need to run `sudo python3 setup.py install` from the twint directory 

That worked for me

I had the same issue above:

Command 'twint' not found, did you mean:
command 'twine' from deb twine
Try: sudo apt install
