### ISSUE TITLE
results are not limited by limit parameter

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#119]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
import twint

c = twint.Config()

# equivalent to `-s` bitcoin    para hacer el or %20OR%20  El %20 es un AND lógico
c.Search = "3dprinter"
   

c.Since = "2017-09-01"
c.Until = "2017-09-2"
c.Count = True
#c.Lang = "es"
c.Limit = "20"

twint.run.Search(c) #obtiene los tweets y obtiene los datos de los usuarios que generan esos tweets

print("PROCESO FINALIZADO recoleccion tweets LANG ES")

### Description of Issue
I want to llimit the results to 20 or any other number (40,60, etc.) but it does not stop, it gives all the results. 
I tried  also with c.Limit = 20 with the sam results

### Environment Details
>Using Windows, Linux? linux What OS version? ubuntu Running this in Anaconda? no Jupyter Notebook? no Terminal? yes

**Comment by haccer** [comment]
Thanks @Nestor75 
There was a misplacement of the `if` statement. It's all fixed now.

**Comment by Nestor75** [comment]
it's great how you support this code. I work with many profesional service lines which are far far away from you in terms of support quality . congrats :)
