### ISSUE TITLE
error in search.py  using until parameter and its solution

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#120]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
 if get.Limit(self.config.Limit, self.count):
                    self.d._until = self.d_until - _days
                    self.feed = [-1]
### Description of Issue

```
.py", line 55, in main
    self.d._until = self.d_until - _days
AttributeError: 'Search' object has no attribute 'd_until'
```

in search.py line 55
```
 if get.Limit(self.config.Limit, self.count):
                    self.d._until = self.d_until - _days
                    self.feed = [-1]
```
there is a . left

the correct code is 
```
 if get.Limit(self.config.Limit, self.count):
                    self.d._until = self.d._until - _days
                    self.feed = [-1]
```
### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
Please confirm

**Comment by haccer** [comment]
Thanks @Nestor75

**Comment by Nestor75** [comment]
you most welcome :)
