### ISSUE TITLE
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by plakythebirb** [haccer/twint#1214]
Hi. I use Windows 10. I'm trying to run a simple "-u" command to scrape a user profile, no special searches, but it results in this string of errors:

CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 15 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 15 secs

It then keeps "sleeping" for an increasing amount of times. I've tried multiple users, so it's not just a problem with the specific user I'm trying to scrape. Any help?

**Comment by KingAkeem** [comment]
It appears that the version of `twint` on `pypi` is broken (v2.1.20), https://github.com/twintproject/twint/issues/786#issuecomment-785038462. 

I was able to resolve this issue by installing `twint` directly from the repo by using `pip3 install . -r requirements.txt` (v2.1.21)

**Comment by plakythebirb** [comment]
@KingAkeem 
Inputting "pip3 install . -r requirements.txt" led to this error:
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

Inputting "pip3 install twint -r requirements.txt" led to this error: 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

What am I doing wrong?

**Comment by KingAkeem** [comment]
Where are you running this command? `setup.py` is in the root directory.

**Comment by plakythebirb** [comment]
I'm running it, no modifications, in the Command Prompt.

**Comment by que-sera-sara** [comment]
Hi - I was having the same problem and reinstalled twint via the Git details on the project page (https://github.com/twintproject/twint) (I'm such a newbie forgive the terminology) 

git clone --depth=1 https://github.com/twintproject/twint.git
cd twint
pip3 install . -r requirements.txt

which worked for me :) I hope that helps - I'm very new at this and so excited that I got it to work!

**Comment by KingAkeem** [comment]
https://github.com/twintproject/twint/issues/1214#issuecomment-856160019

I'm asking you which directory that you're running the file in. I know you're running it from the command prompt but are you running it from the root directory of the `twint` repository (you must also be on the latest commit).

**Comment by plakythebirb** [comment]
How do you change directories? Sorry for not knowing much, I'm pretty new to using command programs.

**Comment by KingAkeem** [comment]
You're going to need to clone this repo to your local machine then navigate to the repository using the `cd` command to execute the instructions that I previously stated.

Here's how to clone a repository from GitHub: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository
Here's how to change directories in windows command line along with some other useful commands that you should know: https://www.digitalcitizen.life/command-prompt-how-use-basic-commands/ (changing directories is number 1)

**Comment by plakythebirb** [comment]
Sorry if this question is really stupid, but I can't find Git Bash on Github's downloads page.

**Comment by KingAkeem** [comment]
Have you tried using these instructions? https://git-scm.com/book/en/v2/Getting-Started-Installing-Git (The installing on windows section)

**Comment by plakythebirb** [comment]
Solved!

**Comment by Julianoapsousa** [comment]
Hi,

I resolve this issues just installing the twint using "pip3 install . -r requirements.txt"
