### ISSUE TITLE
profile option with search, since and until options

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#122]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
c.Search = "3dprinter"
#c.Username = "elonmusk" 

c.Since = "2017-09-01"
c.Until = "2017-20-02"
c.Count = True
#c.Lang = "es"
c.Limit = "20"
c.Output = "file.csv"
c.Store_csv = True

twint.run.Profile(c)
### Description of Issue

the profile opcion which gets retweets info only works with username or user_id  but not with search option, right?

the code above gives 0 results but if I use a username it works. 
the opcions since and until does not work with profile option, it always extract data starting in the current day, is that ok?

### Environment Details
>Using Windows, Linux? linux What OS version? ubuntu Running this in Anaconda? noJupyter Notebook? no Terminal? yes

**Comment by pielco11** [comment]
Now as now `Since` and `Until` work for `Search`, this feature is quite new so it needs some work to satisfy our needs.

Thank you for pointing out!

**Comment by haccer** [comment]
The `Profile` option uses an entirely different request that only takes a username parameter, and also very limited or very slow depending on which method you use.

I'll add more details about the Profile option in the Wiki on a later date.
