### ISSUE TITLE
tweets replies info is not stored in the database

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#126]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Description of Issue
I am working in mysql support so I am reviewing again the code and how the info is stored in the DB.

I realized that the tweet replies info is not in the insert query, it should be in line 189 in the db.py file. 

I will share the whole change I am mading with you using the pull request like you told me. 

I hope having the mysql support by the end of this week.

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
What do you mean? Every attribute that `Tweet` has, it's in the `entry`

Can you elaborate, please?

**Comment by haccer** [comment]
lol oops, i missed that. Thanks again, for keeping an eye out @Nestor75

**Comment by pielco11** [comment]
Lol I should go to the oculist

**Comment by Nestor75** [comment]
other point about DB. 

In DB.py the code for creating the followers and following tables are not the same,.

location text, is missed in the followers table info:

CREATE TABLE IF NOT EXISTS
                followers (
                    id integer not null,
                    name text,
                    username text not null,
                    bio text,
								  
                    url text,
                    join_date text not null,
                    join_time text not null,
                    tweets integer,
                    following integer,
                    followers integer,
                    likes integer,
                    media integer,
                    private text not null,
                    verified text not null,
                    avatar text not null,
                    date_update text not null,
                    follower text not null,
                    PRIMARY KEY (id, username, follower)
                );
