### ISSUE TITLE
ISSUE: Calling c.Format = '...' before calling twint.run.Search(c) fails with AttributeError: 'tweet' object has no attribute 'is_retweet'

### ISSUE THREAD

**Issue by cbjrobertson** [haccer/twint#129]
### Command Ran
```
import twint
c = twint.Config()
c.Username = "ColebRob"
c.Format = "Tweet id: {id} | Tweet: {tweet}"
twint.run.Search(c)
```

### Description of Issue
When I run the above lines without the call to `c.Format` it works fine, but fails with:

```
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/twint/format.py", line 16, in Tweet
    output = output.replace("{is_retweet}", str(t.is_retweet))
AttributeError: 'tweet' object has no attribute 'is_retweet'
```
If I add the format call  before running `twint.run.Search()`

### Environment Details
Using OSX 10.13.3 and running twint in IDLE.

**Comment by haccer** [comment]
Thank you @cbjrobertson

**Comment by cbjrobertson** [comment]
Cheers!

**Comment by benaqlan** [comment]
I face the same problem when I apply c.Format = "Tweet id: {id}" 
it gives me a message replace() argument 2 must be str, not int  

any help

**Comment by himanshudabas** [comment]
@benaqlan 
Can you paste the entire error?
So that I can debug it?

**Comment by benaqlan** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-10-cba50c39d9d2> in <module>
     15 c.Store_csv = True
     16 #c.Location = True
---> 17 twint.run.Search(c)

~\AppData\Roaming\Python\Python38\site-packages\twint\run.py in Search(config, callback)
    408     config.Followers = False
    409     config.Profile = False
--> 410     run(config, callback)
    411     if config.Pandas_au:
    412         storage.panda._autoget("tweet")

~\AppData\Roaming\Python\Python38\site-packages\twint\run.py in run(config, callback)
    327         raise
    328 
--> 329     get_event_loop().run_until_complete(Twint(config).main(callback))
    330 
    331 

~\anaconda3\envs\wadahnlp\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     93                 raise RuntimeError(
     94                     'Event loop stopped before Future completed.')
---> 95             return f.result()
     96         finally:
     97             events._set_running_loop(old_running_loop)

~\anaconda3\envs\wadahnlp\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\anaconda3\envs\wadahnlp\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    280                 result = coro.send(None)
    281             else:
--> 282                 result = coro.throw(exc)
    283         except StopIteration as exc:
    284             if self._must_cancel:

~\AppData\Roaming\Python\Python38\site-packages\twint\run.py in main(self, callback)
    233             task.add_done_callback(callback)
    234 
--> 235         await task
    236 
    237     async def run(self):

~\anaconda3\envs\wadahnlp\lib\asyncio\futures.py in __await__(self)
    258         if not self.done():
    259             self._asyncio_future_blocking = True
--> 260             yield self  # This tells Task to wait for completion.
    261         if not self.done():
    262             raise RuntimeError("await wasn't used with future")

~\anaconda3\envs\wadahnlp\lib\asyncio\tasks.py in __wakeup(self, future)
    347     def __wakeup(self, future):
    348         try:
--> 349             future.result()
    350         except BaseException as exc:
    351             # This may also be a cancellation.

~\anaconda3\envs\wadahnlp\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\anaconda3\envs\wadahnlp\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\AppData\Roaming\Python\Python38\site-packages\twint\run.py in run(self)
    284                     elif self.config.TwitterSearch:
    285                         logme.debug(__name__ + ':Twint:main:twitter-search')
--> 286                         await self.tweets()
    287                 else:
    288                     logme.debug(__name__ + ':Twint:main:no-more-tweets')

~\AppData\Roaming\Python\Python38\site-packages\twint\run.py in tweets(self)
    224             for tweet in self.feed:
    225                 self.count += 1
--> 226                 await output.Tweets(tweet, self.config, self.conn)
    227 
    228     async def main(self, callback=None):

~\AppData\Roaming\Python\Python38\site-packages\twint\output.py in Tweets(tweets, config, conn)
    164     elif config.TwitterSearch or config.Profile:
    165         logme.debug(__name__ + ':Tweets:TwitterSearch')
--> 166         await checkData(tweets, config, conn)
    167     else:
    168         logme.debug(__name__ + ':Tweets:else')

~\AppData\Roaming\Python\Python38\site-packages\twint\output.py in checkData(tweet, config, conn)
    135         return
    136     if datecheck(tweet.datestamp + " " + tweet.timestamp, config):
--> 137         output = format.Tweet(config, tweet)
    138         if config.Database:
    139             logme.debug(__name__ + ':checkData:Database')

~\AppData\Roaming\Python\Python38\site-packages\twint\format.py in Tweet(config, t)
     21         output = output.replace("{hashtags}", ",".join(t.hashtags))
     22         output = output.replace("{cashtags}", ",".join(t.cashtags))
---> 23         output = output.replace("{replies}", t.replies_count)
     24         output = output.replace("{retweets}", t.retweets_count)
     25         output = output.replace("{likes}", t.likes_count)

TypeError: replace() argument 2 must be str, not int

yes I'm using the latest installation

**Comment by benaqlan** [comment]
This is the command

c = twint.Config()
c.Format = 'Twitter id: {id}'
c.Search = 'thalassemia screening'
c.Lang = 'en'
c.Pandas = True
c.Limit = 100
c.Store_object = True
twint.run.Search(c)

**Comment by benaqlan** [comment]
the second thing I want to ask how to let the location appear  in the tweet

**Comment by himanshudabas** [comment]
> ---> 23 output = output.replace("{replies}", t.replies_count)
24 output = output.replace("{retweets}", t.retweets_count)
25 output = output.replace("{likes}", t.likes_count)
>
>TypeError: replace() argument 2 must be str, not int

This will be fixed once #1005 gets merged.

**Comment by Manikya-Varshney** [comment]
I'm still getting the same issue while calling Format.
Command Ran:
config.Format = "Tweet id: {id} | Date: {date} | Time: {time} | Tweet: {tweet}"

Error:
TypeError: replace() argument 2 must be str, not int

**Comment by Manikya-Varshney** [comment]
@himanshudabas 

I'm still getting the same issue while calling Format.
Command Ran:
config.Format = "Tweet id: {id} | Date: {date} | Time: {time} | Tweet: {tweet}"

Error:
TypeError: replace() argument 2 must be str, not int

Using Ubuntu 20.04 and running Twint 2.1.20 on Jupyter Notebook.
