### ISSUE TITLE
bug: adding the retweet flag results in a path error

### ISSUE THREAD

**Issue by nicolecheng** [haccer/twint#130]
### Command Ran
`$ python3 twint/Twint.py -u liamcs98 --database tweets.db --retweets`

### Description of Issue
The command works fine until the --retweets flag is tacked on. The same error exists for the --profile-full flag.
**This is the error generated:**
`Traceback (most recent call last):`
`  File "twint/Twint.py", line 181, in <module> `
`    main()`
`  File "twint/Twint.py", line 172, in main`
`    _userlist = loadUserList(args.userlist, "profile")`
`  File "twint/Twint.py", line 64, in loadUserList`
`    if os.path.exists(os.path.abspath(ul)):`
`  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 371, in abspath`
`    path = os.fspath(path)`
`TypeError: expected str, bytes or os.PathLike object, not NoneType
`
### Environment Details
MacOS terminal

**Comment by pielco11** [comment]
Thank you for pointing out, should work now!
