### ISSUE TITLE
[REQUEST] Pandas dataframe output functionality

### ISSUE THREAD

**Issue by cbjrobertson** [haccer/twint#132]
It would be really cool if one of the output options was to return the results from running twint to a pandas dataframe, which would allow easier iteration of calls to twint, merging old with new results, saving multiple calls to twint as one csv, controlling your own database structure using easy interfaces between sqlite and pandas.

**Comment by pielco11** [comment]
Csv is slower (both read and write) than HDF5 or Pickle, to store few data you should use csv or json (which are smaller than HDF5 or Pickle) but if you intend to do some data analysis you will probably use a lot of data, since the decision to use HDF5 or Pickle which are really fast

There is more yet to come

Ideas and opinions are welcome

**Comment by cbjrobertson** [comment]
The idea behind being able to have `twint` return its results as a `pandas` dataframe is that you could then operate on your data in whatever way you want, without first writing to `pickle`, `csv`, `HDF5`, then importing again if you want to change the data structure. For instance, for a project I am presently working on, I am periodically iterating through a number of search terms and adding the results to a sqlite database. Because the `sqlite` database option doesn't include a column for the search term which generated each result it is essentially useless. I've solved this by writing to `csv` and then compiling these after each scrape into a `sqlite` database. If I could operate on the data within python before writing it would be must more efficient.

**Comment by pielco11** [comment]
You can use the `twint.Pandas.get()` method to get the Dataframe, use `twint.Pandas.save()` to save (see arguments of the method) and the same to read from saved Dataframe

You do not have to write to a file to operate with the Dataframe

**Comment by cbjrobertson** [comment]
I see the code in the repo, but `Pandas.py` not presently being installed when I run `pip3 install twint`, FYI.

**Comment by pielco11** [comment]
Hmm, maybe @haccer can update the pypi package. In the mean time you can update from the repo with `pip install --upgrade -e git+https://github.com/haccer/twint.git@origin/master#egg=twint`

**Comment by cbjrobertson** [comment]
Great, thanks. However, it appears to be returning an empty data frame. 

### Command Ran
```
>>>import twint
>>>c = twint.Config()
>>>c.Search = 'time'
>>>c.Limit = 5
>>>twint.run.Search(c)
tweet 1,
tweet 2,
tweet ..., 
tweet 5
>>>twint.Pandas.get()
Empty DataFrame
Columns: []
Index: []
>>>
```
Am I using it incorrectly?

**Comment by pielco11** [comment]
Sorry, my bad. You have to add `c.Pandas = True` before `twint.run.Search(c)` 

When completed I'll add everything into the wiki

**Comment by cbjrobertson** [comment]
Amazing. Works perfectly. Thanks.

C

Cole
