### ISSUE TITLE
[request] the content of long tweets is not complete

### ISSUE THREAD

**Issue by sue1981** [haccer/twint#1355]
I have successfully scraped wanted tweets by using key words. However, the long tweets are not complete in content. These tweets end with "...", and the rest of the content is missing. Please help, thank you very much!

**Comment by sue1981** [comment]
here are some examples:

1. Chinese Nutrition for Optimal Health of the Kidney Organ System: Chinese medicine places a great role on nutriti... 
2. Continuing on the emotional aspect of Chinese Medicine, did you know that acupuncture can help with all emotional...

**Comment by minamotorin** [comment]
I ran `twint -s 'Chinese Nutrition for Optimal Health of the Kidney Organ System'` and found [this](https://twitter.com/PhyliciaDidionS/status/218736835600453633).

> Chinese Nutrition for Optimal Health of the Kidney Organ System: Chinese medicine places a great role on nutriti... `http://bit.ly/MF1g4y`

“…” was contained in the original Tweets and there are no lacks.

**Comment by sue1981** [comment]
You are right. Thank you so much!
