### ISSUE TITLE
Error when trying to run TWINT... Python version??

### ISSUE THREAD

**Issue by uberlinc** [haccer/twint#1357]
HI,

When trying to run TWINT, I get the following error:

linc@fink:~/Documents/twint$ twint -u networkchuck -s “raspberry pi”
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/linc/.local/bin/twint", line 5, in <module>
    from twint.cli import run_as_command
  File "/home/linc/.local/lib/python3.8/site-packages/twint/__init__.py", line 14, in <module>
    from . import run
  File "/home/linc/.local/lib/python3.8/site-packages/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/home/linc/.local/lib/python3.8/site-packages/twint/get.py", line 12, in <module>
    from aiohttp_socks import ProxyConnector, ProxyType
  File "/home/linc/.local/lib/python3.8/site-packages/aiohttp_socks/__init__.py", line 5, in <module>
    from .connector import (
  File "/home/linc/.local/lib/python3.8/site-packages/aiohttp_socks/connector.py", line 8, in <module>
    from aiohttp.helpers import CeilTimeout  # noqa
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/home/linc/.local/lib/python3.8/site-packages/aiohttp/helpers.py)

- [] Python version is 3.8.10
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

I ran the install procedure as per the NetworkChuck Youtube video, and then some.
Then I ran:
`pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
sudo apt install pipenv
pipenv install git+https://github.com/twintproject/twint.git#egg=twint

Yes, the path has been updated to include TWINT.

### Environment Details
Running Xubuntu:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04

Can anyone interpret the above error to tell me what is up and what I need to do?

Thanks,

**Comment by uberlinc** [comment]
Anyone??

**Comment by uberlinc** [comment]
Scratch that. 
I've found the solution.

**Comment by mohdragon1** [comment]
what is the solution?

**Comment by uberlinc** [comment]
I googled the error:
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/home/linc/.local/lib/python3.8/site-packages/aiohttp/helpers.py)

... and found some guy who did this:

https://stackoverflow.com/questions/69803757/importerror-cannot-import-name-ceiltimeout-from-aiohttp-helpers

Changing this value did the trick.

It works, but I still can't scrape a lot. 
A Twitter Account that has 20K tweets still only returns a few hundred results.
