### ISSUE TITLE
[QUESTION]:Is there a way to scrape likes/retweet names from a specific tweet? 

### ISSUE THREAD

**Issue by rinkydinkyproject** [haccer/twint#142]
### Command Ran
>NA

### Description of Issue
Trying to see if there is a way to use the tool to scrape likes/retweet users (together OR separately) from a particular tweet. This can be incredibly useful in identifying bots and bot pushes for various analysis scenarios. If there is what would be the appropriate command for it? Regards

### Environment Details
>Environment is various. Mac, Windows, Linux systems.

**Comment by haccer** [comment]
Hi @rinkydinkyproject, 

Yes, you can scrape the number of likes & retweets & even replies from a particular Tweet.

I would go about by doing this by using the "Search" feature, to search for the specific Tweet with `-s`; Or if it's by a particular user, you can include that too with the `-u` option in Twint.py. `--stats` will display the likes, retweets, and replies stats, or you can customize your own format with `--format`.

Custom formatting from Twint.py is very similar to how it's done w/ the module. You can read more about that here: https://github.com/haccer/twint/wiki/Module

**Comment by hudmb** [comment]
I think @rinkydinkyproject wanted to scrape the users who like or retweet, not just the like or retweet counts. If I understood correctly?

**Comment by haccer** [comment]
Oh thank you @hudmb, I misread. 

TWINT doesn't feature that, but I wonder if it's possible

**Comment by hudmb** [comment]
Neat idea actually, but maybe slow and hungry to do?

**Comment by Nestor75** [comment]
I think you could do it with the twitter api and limited to 100 retweets or something like that. tweepy is a good library for that.  maybe you were also thinking in include some twitter api features to complement twint but..... you need api credentials and it has many limitations.

**Comment by rinkydinkyproject** [comment]
Hudmb nailed it. That's correct. Yes the api does offer that, but Twint goes around that limitation. Hence the ask. The idea is tweet link, then twint searches the tweet for names in likes and retweets. Hopefully that makes more sense?

**Comment by SundareshPrasanna** [comment]
I'm looking for something similar.. Is this doable using existing twint features?

**Comment by x00x78** [comment]
Scraping the usernames of retweeters requires authentication to Twitter, therefore I don't think twint would be able to do that as of now, I think.

**Comment by miguelwon** [comment]
@rinkydinkyproject I'm looking for the same feature but I couldn't find that option with Twitter API. Did you manage to solve the problem?

**Comment by x00x78** [comment]
The project did not support fetching the retweeters list when I had last checked. I managed to write this small function to do the job. 

def get_retweeters_list(username, tweet_id):
    # get the data of retweets
    r = requests.get('https://twitter.com/i/activity/retweeted_popup?id='+tweet_id)
    # use the grep in order to get the retweeters
    text = r.text
    x = re.findall('div class=\\\\"account  js-actionable-user js-profile-popup-actionable \\\\" data-screen-name=\\\\"(.+?)\\\\" data-user-id=\\\\"', text)
    return x

Its not the best of the works, but I hope it helps.

**Comment by miguelwon** [comment]
Thanks but this type of solution limits the maximum number of retweeters to 25.

**Comment by pielco11** [comment]
(@x00x78 I edited your comment just to make clear the syntax)

**Comment by pielco11** [comment]
@miguelwon it's limited to the first 25 retweeters because Twitter does not allow you to view more. This limit is imposed by Twitter and not a limit of the script, it can be verified with the browser

**Comment by aminnemati96** [comment]
> The project did not support fetching the retweeters list when I had last checked. I managed to write this small function to do the job.
> 
> ```python
> def get_retweeters_list(username, tweet_id):
>     # get the data of retweets
>     r = requests.get('https://twitter.com/i/activity/retweeted_popup?id='+tweet_id)
>     # use the grep in order to get the retweeters
>     text = r.text
>     x = re.findall('div class=\\\\"account  js-actionable-user js-profile-popup-actionable \\\\" data-screen-name=\\\\"(.+?)\\\\" data-user-id=\\\\"', text)
>     return x
> ```
> 
> Its not the best of the works, but I hope it helps.

Hi,
is it possible to do the same thing to get the list of people that liked the tweet?
