### ISSUE TITLE
[QUESTION] What circumstances make twint collect "almost" all tweets from a profile?

### ISSUE THREAD

**Issue by aaeissa** [haccer/twint#143]
Just curious, hope this is okay to discuss here. I ran a search on a profile with 479 tweets and saved it to a CSV, which only had 336 results. 

I know the project's description says that twint "can fetch almost all tweets," so I'm wondering what causes the "almost" scenarios - like he 336/479 I experienced above.

**Comment by haccer** [comment]
@aaeissa If you collected from the Search option (normal), Tweets that are retweeted are excluded from that (as they dont' appear in Twitter's search).. the Profile options are new and experimental which use different methods to collect their Tweets.. there's been a few reports of them not collecting the total number that appears on the profile count, which is something i have time today to investigate.
