### ISSUE TITLE
[QUESTION] Pandas can't read newest JSON file format by Twint

### ISSUE THREAD

**Issue by willnovan** [haccer/twint#1430]
# Pandas can't read JSON file
I've tried many ways to read the new JSON file format from Twint, but it couldn't and returning error below:

> ValueError: Unexpected character found when decoding array value (2)

It was perfect with the old one where the datas stored in square bracket. Please, do anyone have a solution for this issue?

below is the codes and picture of data stored in json:

> import twint
> import nest_asyncio
> 
> nest_asyncio.apply()
> c = twint.Config()
> c.Store_object = True
> c.Lang = "id"
> c.Limit = 2000
> c.Since = "2022-12-30"
> c.Until = "2023-02-23"
> c.Search = "kebijakan hilirisasi -ekspor"
> 
> c.Output = "researchdataset.json"
> twint.run.Search(c)
![example](https://user-images.githubusercontent.com/58553960/220896204-aa3992ad-7101-4c32-8ddf-791a270a17d6.jpg)

or maybe the problem was from my json that stored the datas like that?

**Comment by jaykaycodes** [comment]
You need
`c.Store_json = True`
and read it back with
`pandas.read_json('researchdataset.json', lines=True)`

**Comment by willnovan** [comment]
> 
It's working, thank you very much!
