### ISSUE TITLE
Problems with importing MySQLdb module / can't get any twint commands to work w/o it

### ISSUE THREAD

**Issue by tosyb** [haccer/twint#148]
Hi,

A similar thread was started but was closed - the solutions worked for others but not for me.

I have tried to run a number of normal twint.py commands, which have worked in the past.

All command (example: $ python3 twint.py -s "suspended solids" -o SS.csv --csv) returns the error:

Traceback (most recent call last):
  File "twint.py", line 12, in <module>
    import twint
  File "/Users/scottburnett/Documents/GitHub/twint/twint/__init__.py", line 11, in <module>
    from . import run
  File "/Users/scottburnett/Documents/GitHub/twint/twint/run.py", line 1, in <module>
    from . import favorites, follow, profile, search
  File "/Users/scottburnett/Documents/GitHub/twint/twint/favorites.py", line 1, in <module>
    from . import feed, get, db, output, verbose, dbmysql
  File "/Users/scottburnett/Documents/GitHub/twint/twint/get.py", line 2, in <module>
    from .output import Tweets, Users
  File "/Users/scottburnett/Documents/GitHub/twint/twint/output.py", line 3, in <module>
    from . import db, elasticsearch, format, write, Pandas, dbmysql
  File "/Users/scottburnett/Documents/GitHub/twint/twint/dbmysql.py", line 2, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'

I have tried numerous different approaches to installing MySQL / MySQLdb and keep on getting similar error messages:

> $ pip install mysql
> Collecting mysql
>   Using cached 
> https://files.pythonhosted.org/packages/06/ef/c4efbf2a51fb46aba9be03a973638d9539c9ca10a5259b2cbb1a66133b2e/mysql-0.0.1.tar.gz
> Collecting MySQL-python (from mysql)
>  Using cached 
> https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>      File "<string>", line 1, in <module>
>      File "/private/var/folders/hb/rq81vm0x3_d74yhgf2b8pr_00000gn/T/pip-install-efjfkc9o/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
>      File "/private/var/folders/hb/rq81vm0x3_d74yhgf2b8pr_00000gn/T/pip-install-efjfkc9o/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
>    ModuleNotFoundError: No module named 'ConfigParser'
    
    ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hb/rq81vm0x3_d74yhgf2b8pr_00000gn/T/pip-install-efjfkc9o/MySQL-python/

Attempts to install the ConfigParser module appear to be successful - but then I get the same error message when I try to install MySQL again.

Environment Details:
OS = Mac High Sierra 10.13.4 
Running commands in Terminal

Thanks,
Scott

**Comment by haccer** [comment]
@tosyb 

I reverted the master branch to the previous stable commit. Everything should go back to working fine, sorry about that

**Comment by tosyb** [comment]
Hi Cody

Thanks so much - that's awesome. It now works again. Love your work.

Cheers,
Scott
