### ISSUE TITLE
UserID as data column

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/twint#57]
For ease of retrieval, it would be great if UserID is used for getting tweets (instead of only username).
Same can be said for TweetID, reply/quote TweetID etc.

**Comment by pielco11** [comment]
Do you mean in Elasticsearch or something?

**Comment by DonaldTsang** [comment]
I meant in CSV

**Comment by haccer** [comment]
User IDs have been [added](https://github.com/haccer/twint/commit/83fbf39fc610b5944e4bd005dd4eb29a22420dc7)!

**Comment by DonaldTsang** [comment]
Nice!
