### ISSUE TITLE
Month Scrape Limit

### ISSUE THREAD

**Issue by dleeftink** [haccer/twint#64]
It seems tweet scraping is limited to a month back from the specified date, even when using the following commands:

python twint.py -u BBC --since 2006-03-21 -o BBC.csv --csv
python twint.py -u BBC --since 2006-03-21 --until 2017-06-01 -o BBC.csv --csv

This might be an issue, or am I overlooking an option?

I am running Twint on Windows 10, with Python 3.6.4 (Anaconda 64 bit).

**Comment by rescog** [comment]
I have the same problem with Twint while the previous Tweep release seems to work with older posts

**Comment by pielco11** [comment]
Hi all and thanks for reporting,

in the `while _since < _until` loop, after `else` remove `break` . This should fix the problem. 

I firstly added the feature as this, but maybe this breaks the code somehow with the newest features (since a `break` was added). I'm going to fix this.

**Comment by haccer** [comment]
I have a quick fix, will update in a few mins

**Comment by haccer** [comment]
Fixed in this [commit](https://github.com/haccer/twint/commit/5eec17cd8bf262712f4c7cf52e3ab6d84aa156bd)

Opted for a seperate loop

**Comment by dleeftink** [comment]
Thanks for the fix! This is a nifty piece of software

**Comment by haccer** [comment]
Thank you :)
