### ISSUE TITLE
Doubt about how i can stop the script without lose the content 

### ISSUE THREAD

**Issue by naocaio** [haccer/twint#65]
This is not an issue specifically, but a doubt. How i can stop the script after a time, without lose the content already scraped?
Again, thanks for all dedication writing this code!

**Comment by haccer** [comment]
If I'm understanding the question correctly, 

You could save the output to a file with the`-o` parameter.

**Comment by naocaio** [comment]
Cody, i wanna take a conversation better with you about twint, because i think comment here can be annoying. It's ok for you?  How we can do it?

**Comment by haccer** [comment]
@naocaio you can DM me on Twitter: @now or we can follow up via email: codyzacharias@pm.me
