### ISSUE TITLE
Some questions regarding CSV

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/twint#68]
Question:
1. Are pipe character `|` properly escaped when dumping output to CSV (for compatibility)?
2. Why are Emojis represented as `<Emoji: blah>` instead of proper Unicode?
3. Can some of the link abbreviations be unpacked to the original form, or put on a seperate column?
    - https://github.com/haccer... should show the whole link in a separate column
    - https://t.co/ur1c0de5 should be replaced by the redirected link or have it on a separate column.

**Comment by hpiedcoq** [comment]
Hi 

1. I initially wrote the patch to replace the comma ',' by a pipe '|', because many tweets add a comma in their text, that would be interpreted as a column.
Pipes are pretty uncommon in tweets so you should not find any difficulties of parsing.

3.For the t.co urls, you're definitely right and that's something I planned to do but didn't for a question of time at the moment.

**Comment by haccer** [comment]
Thanks @DonaldTsang

**Comment by hpiedcoq** [comment]
@haccer I wrote a 2way solution for this enhancement : 

- 1st approach would be to escape the pipe in the code. I personally think it produces a weird table, bot very aestethical.

-2nd one is to quote every thing in the csv file. (quoting=csv.QUOTE_ALL option). 

What do you think?

**Comment by haccer** [comment]
Hi @hpiedcoq I just saw this lol. the 2nd option looks good.

**Comment by haccer** [comment]
> Are pipe character | properly escaped when dumping output to CSV (for compatibility)?

I've changed to delimiter to ',' and entries are [now](https://github.com/haccer/twint/commit/655a6c46775fb109ca196770b501a14dcdaa9c14) being wrapped around quotes.

> Why are Emojis represented as <Emoji: blah> instead of proper Unicode?

I'm not going to change this, Emoji's don't display well one some machines (like mine) and I prefer them as text 

> Can some of the link abbreviations be unpacked to the original form, or put on a seperate column?
> https://github.com/haccer... should show the whole link in a separate column
> https://t.co/ur1c0de5 should be replaced by the redirected link or have it on a separate column.

From what I've been seeing recently, the links being output are the complete URLs... -> Even when they have "..." at the end

**Comment by haccer** [comment]
Okay, in the CSV now: The delimiter is "," ; not everything is wrapped around quotes, but if there's a comma in the text, the field gets wrapped around quotes.

**Comment by miguelwon** [comment]
> For #2, he Emojis can be extracted by picking the "alt" tag of the Twitter custom emoji pictures.

Sorry, but do you have any suggestion about how to do such thing? I need to tokenize the tweet, but a standard tweets tokenizer (such as the tokenizer from nltk) don't recognize the `<Emoji: blah>` and therefore I need to convert the emoji title to its unicode and replace the respective text.

**Comment by haccer** [comment]
@miguelwon my new laptop can interpret the emojis now, so I'll be adding this pretty soon
