### ISSUE TITLE
Not getting data from a username

### ISSUE THREAD

**Issue by blind0wl** [haccer/twint#74]
I ran twint against a username yesterday and it worked great.  Today I'm trying to do the same and the command is just sitting there not doing anything.  If I choose another username it seems to work.  I'm not seeing anywhere where it will show a log file to maybe try and debug the issue or find out why it isn't working now.

username is @rusthackreport

Cheers

**Comment by pielco11** [comment]
As you can see [here](https://twitter.com/search?f=tweets&q=from%3Arusthackreport) it seems to be a problem with Twitter itself and not Twint, I hardly find a reason why Twitter is not showing results. If I'll find something I'll keep you updated.

Cheers

**Comment by 4sakura** [comment]
Maybe a Shaddowbanned Account?
