### ISSUE TITLE
problem with -o parameter in the new version released today does not work

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#77]
### Initial Check 
Make sure you've checked the following.

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.

### Command
python twint.py -u nestorpomar  --output  file.csv --csv
python twint.py -u nestorpomar  -o  file.csv --csv

### Description of Issue
with the previous TWINT version I don't have any problem in writting CSV files
I just installed the new version released today and when I use -o or --output , the execution gives the following error message:

Traceback (most recent call last):
  File "twint.py", line 104, in <module>
    main()
  File "twint.py", line 64, in main
    if args.csv and args.o is None:
AttributeError: 'Namespace' object has no attribute 'o'

If I try with the previous version it works without probleam

### OS Details
ubuntu 16

**Comment by pielco11** [comment]
With the newer version, Twint is module so you have to do something like this:

```python
import twint

c = twint.Config()

c.Username = "nestorpomar"
c.Store_csv = True
c.Output = "out.csv"

twint.Search(c)
```

For the interactive mode you can still use old version.

**Comment by haccer** [comment]
@Nestor75 sorry about that lol, I just fixed the issue in the latest [commit](https://github.com/haccer/twint/commit/f36b6ea6a2f8dd32adf13491d5ebd3751a2e0283).

@pielco11 the new [twint.py](https://github.com/haccer/twint/blob/master/twint.py) uses the module, so everything should work like before... but a bit faster.
