### ISSUE TITLE
[REQUEST] new fields to CSV, JSON and DB. Header in CSV - mod - modified coded included

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#78]
### Initial Check 
Make sure you've checked the following.

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint. (I realized you made some changes in the latest hours so it's not the latest but yesterday version)

If this is a feature request please specify in the title:

Example:
> [REQUEST] 
I want to get and store some fields I think your code doesn't do it out of the box. 
The fields are:
- user_id
- mentions
- permanent link

a part from that I want to include a header in the CSV output fields  with what is it each colum but only if the file does not exist. 

I want to share with you the modificatios I did just in case you consider they could be interesting for you and the rest of the people. 

**I checked for CSV files and JSON but not for storing the date in a database**
in bold the file and what I modified / included
==================
file: **db.py** (it confuse my as the code is commented....)

**import os**

table_tweets = """
			CREATE TABLE IF NOT EXISTS
				tweets (
					id integer primary key,
					date text not null,
					time text not null,
					timezone text not null,
					user text not null,
					tweet text not null,
					replies integer,
					likes integer,
					retweets integer,
					hashtags text,
				**mentions text
                                        userid integer,
					permanentlink text

				);**
“””

def tweets(conn, Tweet):
	try:
		cursor = conn.cursor()
		entry = (Tweet.id, 
				Tweet.datestamp,
				Tweet.timestamp,
				Tweet.timezone,
				Tweet.username,
				Tweet.tweet,
				Tweet.replies,
				Tweet.likes,
				Tweet.retweets,
				",".join(Tweet.hashtags),
                        	**",".join(Tweet.mentions),
                                Tweet.userid,
                        	Tweet.permanentlink,)**
		cursor.execute("INSERT INTO tweets VALUES(?,?,?,?,?,?,?,?,?,?,**?,?,?**)", entry)

	conn.commit()
	except sqlite3.IntegrityError:
		pass

====================
file **tweet.py**

class Tweet(object):
	id = ""
	date = ""
	datestamp = ""
	time = ""
	timestamp = ""
	timezone = ""
	username = ""
	tweet = "" # Text
	replies = "0"
	likes = "0"
	retweets = "0"
	hashtags = ""
	**mentions = ""
	userid = ""
	permanentlink = ""**

==================
output.py

def writeJSON(Tweet, file):
	data = {
			"id": Tweet.id,
			"date": Tweet.datestamp,
			"time": Tweet.timestamp,
			"timezone": Tweet.timezone,
			"username": Tweet.username,
			"tweet": Tweet.tweet,
			"replies": Tweet.replies,
			"retweets": Tweet.retweets,
			"likes": Tweet.likes,
			"hashtags": ",".join(Tweet.hashtags),
                      **",".join(Tweet.mentions),
                          Tweet.userid,
            	         Tweet.permanentlink]**
	with open(file, "a", newline='', encoding="utf-8") as json_file:
		json.dump(data, json_file)
		json_file.write("\n")

def writeCSV(Tweet, file):
	data = [
			Tweet.id,
			Tweet.datestamp,
			Tweet.timestamp,
			Tweet.timezone,
			Tweet.username,
			Tweet.tweet,
			Tweet.replies,
			Tweet.retweets,
			Tweet.likes,
			",".join(Tweet.hashtags),
                     **",".join(Tweet.mentions),
                         Tweet.userid,
            	         Tweet.permanentlink]
         if not (os.path.exists(file)):
            		with open(file, "a", newline='', encoding="utf-8") as csv_file:
                        		writer = csv.writer(csv_file, delimiter="\t")
                        writer.writerow(["tweetid", "date", "time", "timezone", "user","text",\
                                                        "replies","retweets","likes", "hashtags",\
                                                        "mentions", "user_id", "permanent Link"])
            		            writer.writerow(data)
        
            else:
                       with open(file, "a", newline='', encoding="utf-8") as csv_file:
                            writer = csv.writer(csv_file, delimiter="\t")
                            writer.writerow(data)**

**def getMentions_nes(text):
	mentions = re.findall(r'(?i)\@\w+', text, flags=re.UNICODE)
	return mentions
	#return ",".join(mentions)**

# Sort HTML
def getTweet(tw, config):
	t = Tweet()
	t.id = tw.find("div")["data-item-id"]
	t.date = getDate(tw)
	if config.Since and config.Until:
		if (t.date.date() - datetime.datetime.strptime(config.Since, "%Y-%m-%d").date()).days == -1:
			# mitigation here, maybe find something better
			sys.exit(0)
	t.datestamp = t.date.strftime("%Y-%m-%d")
	t.time = getTime(tw)
	t.timestamp = t.time.strftime("%H:%M:%S")
	t.username = tw.find("span", "username").text.replace("@", "")
	t.timezone = strftime("%Z", gmtime())
	for img in tw.findAll("img", "Emoji Emoji--forText"):
	img.replaceWith("<{}>".format(img['aria-label']))
	t.tweet = getMentions(tw, getText(tw))
	t.hashtags = getHashtags(t.tweet)
	**t.mentions = getMentions_nes(t.tweet)**
	t.replies = getStat(tw, "reply")
	t.retweets = getStat(tw, "retweet")
	t.likes = getStat(tw, "favorite")
        **t.userid = tw.find("div")["data-user-id"]
        t.permanentlink  = 'https://twitter.com' + tw.find("div")["data-permalink-path"]**
	return t

===================

### OS Details
Using Windows, Linux?  Linux
What OS version? Ubuntu 16

thank you very much for your help

**Comment by Nestor75** [comment]
some bold were not aplied and there are ** ** instead of the bold font :(

**Comment by Nestor75** [comment]
Sure,  I will and sorry for the inconvenience. 
Thank you very much for your help 
Best regards 
Nestor

**Comment by pielco11** [comment]
No problems, Issues are good for requests and proposal but for code edits PRs fit at best our needs!

**Comment by haccer** [comment]
@Nestor75 I've also added the tweet link too. I feel like right now adding mentions is not really needed, but I might feel different in the future. Thanks for the suggestions.

**Comment by Nestor75** [comment]
that's great :) I think including the header in the CSV file if the file does not exist could be very useful.

you would hace to import os and use a code like this but with the popper header fields in the output.py file :

if not (os.path.exists(file)):
                 with open(file, "a", newline='', encoding="utf-8") as csv_file:
                       writer = csv.writer(csv_file, delimiter="\t")
                       writer.writerow(["tweetid", "date", "time", "timezone", "user","text",
                       "replies","retweets","likes", "hashtags",
                        "mentions", "user_id", "permanent Link"])
                         writer.writerow(data)

        else:
                   with open(file, "a", newline='', encoding="utf-8") as csv_file:
                        writer = csv.writer(csv_file, delimiter="\t")
                        writer.writerow(data)

**Comment by haccer** [comment]
@Nestor75 Thanks, this led to me changing another issue w/ csv while making it aesthetically pleasing
