### ISSUE TITLE
Using Store_csv

### ISSUE THREAD

**Issue by wagerpascal** [haccer/twint#79]
I am interested in using Twint in its module form to scrape some user data into a CSV form. Currently, I am using the following test code: 
```
import twint

# Configure
c = twint.Config()

c.Store_csv = True
# equivalent to `-s` bitcoin
c.Search = "Trump"
# Custom output format

c.Format = "Tweet id: {id} | Username: {username}"

# Run
twint.Search(c)
```
Right now, I am unsure of how exactly to use the Store_csv function, and am not seeing any output besides in my terminal - am I able to specify the name of the CSV file, and how do I ensure that it is actually running?

**Comment by haccer** [comment]
Hi,

You need to specify a file with `c.Output`. So your code should look something like this:
```python
import twint

c = twint.Configure()

c.Store_csv = True
c.Output = "trump.csv"
c.Search = "Trump"

twint.Search(c)
```

**Comment by haccer** [comment]
@wagerpascal no but I think i can make that

**Comment by haccer** [comment]
@wagerpascal Okay, I've added support for custom CSV fields. This was a really good idea.

Here's an example of how to incorporate it:
```python
#!/usr/bin/python3
import twint

c = twint.Config()

c.Username = "twitter"
c.Store_csv = True
# CSV Fieldnames
c.Custom_csv = ["id", "user_id", "username", "tweet"]
c.Output = "twitter.csv"

twint.Search(c)
```

More info is on the [wiki](https://github.com/haccer/twint/wiki/Module) if you need.
