### ISSUE TITLE
Conversion to Emojis

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/twint#85]
Regarding the consistency of Emoji quotes with arrow brackets, is it possible to...
1. Make it consistent such that ALL emojis uses arrow bracket quotes, or  
2. Make it such that ALL emojis are rendered in plaintext  

I know option #2 is not good for rendering, but it is good for emoji feature extraction.  
Maybe it is possible to make a converter to switch between the two?
### List of characters that can be considered "Emojis"
* `\u2190-\u21ff` # Arrows block
* `\u2200-\u22ff` # Mathematical Operators
* `\u2300-\u23ff` # Miscellaneous Technical
* `\u2440-\u245f` # Optical Character Recognition
* `\u2500-\u259f` # "Box Drawing" or "Block Elements"
* `\u25a0-\u25ff` # Geometric Shapes block
* `\u2600-\u26ff` # Miscellaneous Symbols
* `\u27c0-\u27ef` # Miscellaneous Mathematical Symbols-A
* `\u27f0-\u27ff` # Supplemental Arrows-A
* `\u2900-\u297f` # Supplemental Arrows-B
* `\u2980-\u29ff` # Miscellaneous Mathematical Symbols-B
* `\u2a00-\u2aff` # Supplemental Mathematical Operators
* `\u2b00-\u2bff` # Miscellaneous Symbols and Arrows
* `\U0001f300-\U0001f5ff` # Miscellaneous Symbols and Pictographs
* `\U0001f600-\U0001f64f` # Emoticons
* `\U0001f650-\U0001f67f` # Ornamental Dingbats
* `\U0001f680-\U0001f6ff` # Transport and Map Symbols
* `\U0001f800-\U0001f8ff` # Supplemental Arrows-C
* `\U0001f900-\U0001f9ff` # Supplemental Symbols and Pictographs

**Comment by haccer** [comment]
Sorry @DonaldTsang ,

I don't plan on adding emoji conversion at this time. As I stated early, some devices (like mine) don't render them properly, and I'd prefer a description of the emoji rather than it appearing as [], not knowing what it is.
