### ISSUE TITLE
[REQUEST] Parse out @mentions as comma separated list

### ISSUE THREAD

**Issue by hudmb** [haccer/twint#89]
It would be great if you could parse out all the @mentions in a tweet as a comma separated list (as you do for hashtags). Even better if you could remove the '@' symbol and lowercase them all too :)

**Comment by haccer** [comment]
Okay this has been added

**Comment by hudmb** [comment]
Perfect, thanks!

**Comment by hudmb** [comment]
Hi! Is there a command for this? If not, I don't see a list of extracted @ usernames in a column in an output csv file.
