### ISSUE TITLE
AttributeError: module 'twint' has no attribute 'Config'

### ISSUE THREAD

**Issue by miguelwon** [haccer/twint#92]
Hi,

I have installed twint with 

`pip3 install twint`

that resulted in a successful installation: 

`Successfully installed twint-1.1.2.3`

but when I tried to run the example with [twint.py](https://github.com/haccer/twint/blob/master/twint.py) script:

`python twint.py -g="48.880048,2.385939,1km" -o file.csv --csv`

I got the error:

```
Traceback (most recent call last):
  File "twint.py", line 148, in <module>
    main()
  File "twint.py", line 136, in main
    c = initialize(args)
  File "twint.py", line 62, in initialize
    c = twint.Config()
AttributeError: module 'twint' has no attribute 'Config'
```

**Comment by haccer** [comment]
Thank you!

The issue was the name of the script had the same name as the module, so it would try to import itself. Simply renaming the script to something not 'twint' resolves the issue. In the repository, I renamed twint.py to Twint.py.

**Comment by KorayTugberk-g** [comment]
Hello, I couldn't find the location of the Twint.py file. Does anyone have an idea?

**Comment by pielco11** [comment]
@KorayTugberk-g it's part of an old version, code changed a lot since then

**Comment by Pranit-Bhujel** [comment]
> Thank you!
> 
> The issue was the name of the script had the same name as the module, so it would try to import itself. Simply renaming the script to something not 'twint' resolves the issue. In the repository, I renamed twint.py to Twint.py.

This actually solved my issue. Thanks man!
