### ISSUE TITLE
Graph Visualization and DB

### ISSUE THREAD

**Issue by Schneider32** [haccer/twint#95]
Thank you for the great "program"!!

What I still have problems that no graph is created. Where does the DB file have to be so that it can be found by the Graph application?

I have tried several things but no graph is drawn.

**Comment by pielco11** [comment]
Hello @Schneider32 

If you did not build the source you can do `CRTL + SHIFT + I` to open the Dev panel as see what errors you are having. 

The DB file must be under `twint/graph` directory, if you try to load a DB from a DB file that it's not in that directory, `sqlite3` will create an empty file with that name (that's how databases work)
