### ISSUE TITLE
[REQUEST] allow list of usernames in a csv as an input

### ISSUE THREAD

**Issue by sahildeo** [haccer/twint#96]
Would it be possible to run this with multiple user names? maybe from a csv/txt file as an input? thanks!

**Comment by haccer** [comment]
This sounds good. I'll add it when I have the time.

**Comment by sahildeo** [comment]
Sure. Thanks!

**Comment by pielco11** [comment]
The `userlist` arg overrides `username`. Twint checks if the given arg is a file that exists and if not a string with values separated by a `,` is expected.

If a user parses file the values need to be in line by line (separated by a `\n`)
