### ISSUE TITLE
Times out on large queries

### ISSUE THREAD

**Issue by alexsieusahai** [haccer/twint#98]
### Initial Check 
Make sure you've checked the following.

- [X] Python version is 3.5 or higher.
- [X] Using the latest version of Twint.

### Command
python twint.py -s "fracking" --since 2010-01-01 --until 2013-12-30

### Description of Issue
Times out. My anaconda prompt crashed after I ran an alternative command, so I couldn't get output for you. I'm going to rerun the command and paste the logs after it times out. 

### OS Details
Windows

**Comment by alexsieusahai** [comment]
And I have a workaround using the module, this is just a nice qol bug. I'll attempt to solve it and if I get no where I'll show what I got so far and let you do whatever you want with it.

**Comment by pielco11** [comment]
Timeouts can occur cause of connection, can you replicate the errors? If so, can you post here what you get?

Plus, can you describe the workaround? This might help us to improve the code
