### ISSUE TITLE
Cannot save .csv file

### ISSUE THREAD

**Issue by Tabs16** [haccer/twint#99]
I am using ubuntu 16.04 and trying the example which has the following code 
`import twint
c = twint.Config()
c.Username = "twitter"
c.Limit = 20
c.Store_csv = True
c.Custom_csv = ["id", "user_id", "username", "tweet"]
c.Output = "twitter.csv"`
I donot understand why the data is not getting stored in the "twitter.csv" file, in fact the file is not generated.
TIA!

**Comment by haccer** [comment]
Looks like you're missing: 
```python
twint.Search(c)
```
